### PR TITLE
North_Saami.csv -> tsv

### PR DESCRIPTION
**Pull request by HedvigS**
North_Saami.csv was tab separated, I've changed it to comma separated as the others.

### CODE REVIEW

**Comment by xrotwang** [comment]
The cldfbench turning this data into CLDF can handle both delimiters, so this change isn't necessary from my POV. It also changes **all** lines of the file which tends to make history less useful.

**Comment by HedvigS** [comment]
> The cldfbench turning this data into CLDF can handle both delimiters, so this change isn't necessary from my POV. It also changes **all** lines of the file which tends to make history less useful.

Understood.

For me to do this UraTyp Grambank matching, it is easier if all sheets are uniformly formatted.

**Comment by xrotwang** [comment]
Ideally, I think, this matching would be done based on the UraTyp CLDF dataset. Then you'd get uniformity, relations to sources, etc. That's one of the reasons why I'd prefer merging **released** UraTyp data into Grambank.

**Comment by HedvigS** [comment]
> Ideally, I think, this matching would be done based on the UraTyp CLDF dataset. Then you'd get uniformity, relations to sources, etc. That's one of the reasons why I'd prefer merging **released** UraTyp data into Grambank.

Like I said before, we have different understandings of what we agreed on last year. I leave it to Miina to decide.

**Comment by HedvigS** [comment]
I also found that Central_veps has semi-colons and I changed to commas.

I understand that the later CLDF-workflow can probably already manage this. I hope you can be patient and help me here by making these small edits, even though it does log line-changes for every row.

**Comment by xrotwang** [comment]
> I understand that the later CLDF-workflow can probably already manage this. I hope you can be patient and help me here by making these small edits, even though it does log line-changes for every row.

Ok with me. @MiinaNo can merge the PR if that's of with her editing workflow.

**Comment by HedvigS** [comment]
(If someone could give me read access to this repos that would be brill, then I can just branch instead of fork and I can tag reviewers (I think))

**Comment by xrotwang** [comment]
I'm not an admin of this repo.

**Comment by MiinaNo** [comment]
@HedvigS I have now given you access to uratyp-1

**Comment by MiinaNo** [comment]
@HedvigS, one more thing, it seems that I fixed some sources after you had forked the repository. I noticed this also when comparing the differences. Otherwise things looked fine, only the very final changes had not made it there.

**Comment by HedvigS** [comment]
> @HedvigS, one more thing, it seems that I fixed some sources after you had forked the repository. I noticed this also when comparing the differences. Otherwise things looked fine, only the very final changes had not made it there.

Thanks!

I'll reclone with latest version at origin when I do the overwriting of data-points.

**Comment by MiinaNo** [comment]
> > @HedvigS, one more thing, it seems that I fixed some sources after you had forked the repository. I noticed this also when comparing the differences. Otherwise things looked fine, only the very final changes had not made it there.
> 
> Thanks!
> 
> I'll reclone with latest version at origin when I do the overwriting of data-points.

Great, I will fix a few more sources then (I will do it right away).

**Comment by HedvigS** [comment]
Can this branch be reviewed and if approved merged into main?

**Comment by HedvigS** [comment]
I can't add reviewers or merge in this branch.

**Pull request merged**
